### ISSUE TITLE
Hangman-0.1.0.0 release tarball is incomplete

### ISSUE THREAD

**Issue by peti** [lf94/Hangman#1]
See  http://hydra.cryp.to/build/1064634/log/raw for the build error I got trying to compile this package.

**Comment by lf94** [comment]
Yeah I saw that on Hackage too. I find it weird because running `cabal build` locally works for me. I'll check it out now.

**Comment by lf94** [comment]
There we go, all fixed. I was missing files from "extra-source" in my .cabal file. Sorry about that! I better go upload the new tgz to Hackage too.
